name: Publish Docker Image

on:
  push:
    branches: [ master ]
env:
  IMAGE_NAME: nginx
  REGISTRY: ghcr.io
  VERSION: v8.0
jobs:
  buildImage:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      # - uses: president-business-corp/simple-docker/metadata@trunk
      #   id: metadata
      #   with:
      #     image-name: ${{ env.IMAGE_NAME }}
      #     registry: ${{ env.REGISTRY }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          driver-opts: image=moby/buildkit:master

      - name: log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN}}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Container image
        run: docker buildx build . --file Dockerfile-8.0 --tag $IMAGE_NAME

#       - name: Build and push
#         id: docker_build
#         uses: actions/checkout@v2
#         with:
#           builder: ${{ steps.buildx.outputs.name }}
#           context: Dockerfile-8.0
# #          file: ${{ steps.metadata.outputs.file }} 
#           platforms: ${{ steps.qemu.outputs.platforms }}
#           push: true
#           tags: ${{ steps.metadata.outputs.tags }}
#           build-args: ${{ steps.metadata.outputs.args }}
#           labels: ${{ steps.metadata.outputs.labels }}
          
      
        
      # - name: log into GitHub Container Registry
      #   run: echo "${{ secrets.GITHUB_TOKEN}}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Push image to GitHub Container Registry
        run: |
            IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION
            docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
        # run: |
        #     IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        #     echo IMAGE_ID=$IMAGE_ID
        #     echo VERSION=$VERSION
        #     docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        #     docker tag $IMAGE_NAME $IMAGE_NAME:${{ github.run_id }}
        #     docker push $IMAGE_ID:$VERSION

