name: Publish Docker Image

on:
  push:
    branches: [ master ]
env:
  IMAGE_NAME: nginx
  VERSION: v8.0
jobs:
  buildImage:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          driver-opts: image=moby/buildkit:master
      
      - name: log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN}}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - uses: actions/checkout@v2
      - name: Build Container image
        run: docker buildx build --platform linux/amd64,linux/arm64 --tag ghcr.io/nabad600/nginx:v8.0 -f Dockerfile-8.0 . --push
        
        # run: docker buildx build --platform=linux/amd64 . --file Dockerfile-8.0 --tag $IMAGE_NAME
        
        
      # - name: Push image to GitHub Container Registry
      #   run: |
      #       IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
      #       echo IMAGE_ID=$IMAGE_ID
      #       echo VERSION=$VERSION
      #       docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
      #       docker tag $IMAGE_NAME $IMAGE_NAME:${{ github.run_id }}
      #       docker push $IMAGE_ID:$VERSION
 
      